CUDA_VISIBLE_DEVICES=6 python -m llava.eval.model_vqa_science \
    --model-path /data1/public_data/llava_ckpt/LLaVA-vicuna-7B-v1.3-ScienceQA \
    --question-file /home/wangxinhao/ScienceQA/data/scienceqa/llava_test_QCM-LEA.json \
    --image-folder /home/wangxinhao/ScienceQA/data/scienceqa/images/test \
    --question-file-calibrate /home/wangxinhao/ScienceQA/data/scienceqa/llava_train_QCM-LEA.json \
    --image-folder-calibrate /home/wangxinhao/ScienceQA/data/scienceqa/images/train \
    --answers-file /home/wangxinhao/QVLM/results/tmp/LLaVA-vicuna-7B-v1.3-4bit.jsonl \
    --conv-mode llava_v1 \
    --visual_token_num 128 \
    --add_quant \
    --load-4bit